name: charge_at_home
description: A Flutter app to find residential EV charging stations and let homeowners list their garages as charging providers.

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# ===============================================
# ================ DEPENDENCIES =================
# ===============================================
dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Firebase Core & Auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Maps & Location Services
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # UI & Utilities
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.1.0

  # Form Validation
  form_field_validator: ^1.1.0

# ===============================================
# ============== DEV DEPENDENCIES ===============
# ===============================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# ===============================================
# ============= FLUTTER SETTINGS ================
# ===============================================
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
